# Generated by Django 2.2.26 on 2022-02-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redenvelopes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redenvelopereward',
            name='bank_account',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
